### ISSUE TITLE
Build on Windows

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/netcdf-fortran-feedstock#3]
See https://github.com/Unidata/netcdf-fortran/issues/48#issuecomment-208321745

**Comment by pelson** [comment]
Maybe we can get some help from those in that issue? It would be time well spent for everybody's benefit.

**Comment by ocefpaf** [comment]
We are now using `cmake` on Linux and OS X. The issue with Windows is the Fortran compiler. I don't think we have a proper solution for Fortran on Windows yet.

Ping @gillins, @patricksnape, and @mingwandroid for your opinions and comments on the Fortran issue.

**Comment by mingwandroid** [comment]
IMHO `conda install -c msys2 m2w64-toolchain` is the current best solution for Fortran.

**Comment by ocefpaf** [comment]
> IMHO `conda install -c msys2 m2w64-toolchain` is the current best solution for Fortran.

I will play with that. I believe that having `msys2` in conda-forge will be very valuable. How difficult would that be?

**Comment by mingwandroid** [comment]
Not really difficult, it's just a question of time, something I've not got a lot of. Originally I was pushing for them to be part of `defaults` or rather, linked to `defaults` as a `metachannel`; actually they are in two places at present, `msys2` and `r`!

The recipes are just unpack / repack scripts. They could be imported without much bother. Because of the rolling nature of `MSYS2` there does need to be some centralized control so there's an `msys2-conda-epoch` package which manages dragging everything up to the correct contemporary versions.

I haven't managed to find time to tidy up my script that talks to `pacman` (`pyalpm` and `libalpm` really) and creates the recipes yet. It needs to be part of `conda skeleton` IMHO.

**Comment by ocefpaf** [comment]
> Originally I was pushing for them to be part of `defaults`

:+1: 

Can you point me to your recipes? I might give it a try...

**Comment by mingwandroid** [comment]
Sure, they are here:

https://github.com/conda/conda-recipes/tree/master/msys2

**Comment by MuellerSeb** [comment]
ping.

**Comment by MuellerSeb** [comment]
Is there any progress here? It would be really nice having windows support.

**Comment by beckermr** [comment]
looks like not. If you want to try it, please do! Simply fork the repo and make a PR. Lot's of people on this thread can help solve problems as they arise!

**Comment by jaimergp** [comment]
I am trying my best on #52 with the msys2 compilers. Apparently it's missing some symbols:

```
[ 35%] Linking Fortran executable tst_f77_v2.exe
../fortran/libnetcdff.a(nf_v2compat.c.obj):nf_v2compat.c:(.rdata$.refptr.ncerr[.refptr.ncerr]+0x0): undefined reference to `ncerr'
../fortran/libnetcdff.a(nf_v2compat.c.obj):nf_v2compat.c:(.rdata$.refptr.ncopts[.refptr.ncopts]+0x0): undefined reference to `ncopts'
collect2.exe: error: ld returned 1 exit status
```

This is the same issue observed [in this other attempt](https://github.com/Unidata/netcdf-fortran/issues/48#issuecomment-277710507). As in that case, our [CMake does not find `netcdf.h`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=163441&view=logs&j=f97ca392-d626-52d0-4b2e-4b27aa319a77&t=7b750183-140d-50ae-3ee1-cbef6218bdf6&l=422). Any ideas?

--

__edit__: If I enable CFLAGS/LDFLAGS, CMake finds `netcdf.h` but the `ncerr` error remains. Note that I can't specify any libraries on `CFLAGS` or the linker will fail during CMake:

```batch
set "LDFLAGS=-L%LIBRARY_PREFIX%/lib -Wl,-rpath,%LIBRARY_PREFIX%/lib"
:: Left out: `-lcurl -lhdf5 -lhdf5_hl -ldf -lmfhdf`
set "CFLAGS=-fPIC -I%LIBRARY_PREFIX%/include"
```

**Comment by MuellerSeb** [comment]
The referenced issue is marked for `v1.5.3`, and there is already a related pull request. Maybe this will work with the next release that is hopefully coming soon.

**Comment by MuellerSeb** [comment]
Maybe the new release helps:
https://github.com/Unidata/netcdf-fortran/releases/tag/v4.5.3

**Comment by jaimergp** [comment]
Thanks for the heads up! I'll wait until the regro PR is merged before integrating those changes.

**Comment by jaimergp** [comment]
Unfortunately [the same error is still present on `v4.5.3`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=176386&view=logs&j=f97ca392-d626-52d0-4b2e-4b27aa319a77&t=7b750183-140d-50ae-3ee1-cbef6218bdf6&l=620) :(

**Comment by MuellerSeb** [comment]
Some new hope:
https://github.com/Unidata/netcdf-fortran/pull/268

**Comment by jaimergp** [comment]
It was merged, so now it's a matter of time until v4.5.4!

**Comment by MuellerSeb** [comment]
@jaimergp [v4.5.4](https://github.com/Unidata/netcdf-fortran/releases/tag/v4.5.4) is out :tada:

**Comment by xylar** [comment]
I'm building 4.5.4 without Windows first: #69.  Feel free to follow up with a PR to add Windows.
