### ISSUE TITLE
Broken run_export makes downstream packages uninstallable

### ISSUE THREAD

**Issue by carterbox** [conda-forge/netcdf-fortran-feedstock#75]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Releases 4.6.0_0 and 4.5.4_1 used `pin_compatible() {{ build }}` instead of `pin_subpackage() {{ build }}`. This causes the run_export for packages that build against those releases to be:
```
netcdf-fortran mpi_openmpi_.* # uninstallable package spec
```
instead of 
```
netcdf-fortran 4.6 mpi_openmpi_*  # installable package spec
```
This makes those packages uninstallable because they depend on a version of netcdf-fortran that does not exist. In other words, this error is mostly silent because it makes downstream packages uninstallable. Perhaps downstream packages haven't noticed yet because the solver can choose another solution that avoids those broken packages? But I think they should have failed the install during their rest phase? Regardless I don't know which packages are contaminated with this error which is causing problems with the following pull request.

https://github.com/conda-forge/staged-recipes/pull/20231

The solution is to mark these builds a broken and to try to find the packages which have been contaminated by them OR start a bot migration away from the contaminated versions. Or maybe [the docs say they should be patched?](https://conda-forge.org/docs/orga/guidelines.html#fixing-broken-packages) I'm not familiar with this process.

This error was fixed in 4.6.0_1, but the damage is already done and the broken builds should be pulled.

EDIT: Added note about patching instead of pulling.

**Comment by xylar** [comment]
@carterbox, thanks for this note.  I'm familiar with the patch process, though I'll need to look into run_exports specifically.

**Comment by xylar** [comment]
I will say in my defense that the linter very clearly seemed to indicate that this was a needed change:
https://github.com/conda-forge/netcdf-fortran-feedstock/pull/72#issuecomment-1197656968

```
pin_compatible should be used instead of pin_subpackage for netcdf-fortran because it is not a known output of this recipe: ['netcdf-fortran'].
```

**Comment by carterbox** [comment]
Great! The releases of this package listed above need to be patched so that the `run_exports.json` contains:

```
{"weak": ["netcdf-fortran 4.6.* mpi_mpich_*"]}
```
AND
```
{"weak": ["netcdf-fortran 4.5.* mpi_mpich_*"]}
```

instead of:

```
{"weak": ["netcdf-fortran  mpi_mpich_*"]}
```

Then if we can find the downstream packages that built against these broken packages, we should patch those too. Maybe there is a way to search and replace `{"weak": ["netcdf-fortran  mpi_mpich_*"]}` in packages.

**Comment by xylar** [comment]
@carterbox, I will definitely look into it and try to get this patched ASAP.  Thanks again.

**Comment by carterbox** [comment]
> I will say in my defense that the linter very clearly seemed to indicate that this was a needed change: [#72 (comment)](https://github.com/conda-forge/netcdf-fortran-feedstock/pull/72#issuecomment-1197656968)
> 
> ```
> pin_compatible should be used instead of pin_subpackage for netcdf-fortran because it is not a known output of this recipe: ['netcdf-fortran'].
> ```

Ironically, that is a bug in a lint I wrote to prevent this error from occurring. It was fixed in https://github.com/conda-forge/conda-smithy/pull/1642

**Comment by xylar** [comment]
I see.  I hope this is the only package where I made this mistake but I'll keep an eye out for it.

**Comment by xylar** [comment]
@ocefpaf, do you have an example of patching `run_exports.json` you can point me to?  I'm looking at https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/main/recipe/gen_patch_json.py and not seeing anything like that.

**Comment by ocefpaf** [comment]
Sorry, I don't. We can pull the package, probably easier.

**Comment by xylar** [comment]
> We can pull the package, probably easier.

Yeah, that was all I was able to find examples for.  We need #76 before we do that.

**Comment by xylar** [comment]
Sorry for the delay.  I'm requesting that they be marked as broken in https://github.com/conda-forge/admin-requests/pull/497

**Comment by xylar** [comment]
I believe this has been addressed in recent builds and the offending packages have been marked as broken.
